### ISSUE TITLE
Plugin freezes at the link tracks button

### ISSUE THREAD

**Issue by Vinidata** [Mellowed/get-liked#1]
I did all the steps and it went great as it pulled all the songs, but on the final Spotify page as I tried to link the songs it just loaded and wouldn't let me continue. I tried multiple times on different devices.

**Comment by Mellowed** [comment]
Hey @Vinidata, 

The linking can take some time and the create playlist button will only be available once it has tried to link all the songs. 

I ran a quick test, it took about 2m to lookup a liked playlist of 100  songs in Spotify. There's a small count indicator here:
![image](https://user-images.githubusercontent.com/21101991/218258782-17bb5fa7-27d5-43a9-9f45-4470a7957992.png)

**Comment by Vinidata** [comment]
Im not sure why but this doesn't seem to work for me, I tried two different
emails and two playlists and waited for around ten minutes and the counter
never went up
